const ESCROW_ADDRESS = 'AEC4WDHXCDF4B5LBNXXRTB3IJTVJSWUZ4VJ4THPU2QGRJGTA3MIDFN3CQA'
const IDENTITY_ADDRESS = 'address'

module.exports = {
    ESCROW_ADDRESS: ESCROW_ADDRESS,
    IDENTITY_ADDRESS: IDENTITY_ADDRESS
}