const ESCROW_ADDRESS = '4SLOBT73HGOJMNJPYYDJZSNK5YGH7PGAUAMDJDIASJJSZNYBOQRWMKNA6Q'
const IDENTITY_ADDRESS = '2XECBV6436LU3VFZXKMTKR5G3ZIC2OTUJZGEUQAYYBN4RUPU64ECESABFY'

module.exports = {
    ESCROW_ADDRESS: ESCROW_ADDRESS,
    IDENTITY_ADDRESS: IDENTITY_ADDRESS
}