const ESCROW_ADDRESS = 'B2UVIDGYBKZJHZYF62EVEQKOWKRK4RVXVMMW4TICLZ5XYQ6G2CFZ6G673Y'
const IDENTITY_ADDRESS = 'identity-address'

module.exports = {
    ESCROW_ADDRESS: ESCROW_ADDRESS,
    IDENTITY_ADDRESS: IDENTITY_ADDRESS
}