const ESCROW_ADDRESS = '4SLOBT73HGOJMNJPYYDJZSNK5YGH7PGAUAMDJDIASJJSZNYBOQRWMKNA6Q'
const IDENTITY_ADDRESS = 'AT35IAAPOLIPTZAFMFX6M55GJD3DMFCMF2O4PLBWA26SM2MPNHK3A2SE3E'

module.exports = {
    ESCROW_ADDRESS: ESCROW_ADDRESS,
    IDENTITY_ADDRESS: IDENTITY_ADDRESS
}
